# Generated by Django 3.1.6 on 2021-02-22 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='service_category',
            new_name='service_category_id',
        ),
    ]
