# Generated by Django 3.1.6 on 2021-02-08 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assigndatacollector',
            old_name='address',
            new_name='area',
        ),
    ]
