# Generated by Django 3.1.6 on 2021-02-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectdata',
            name='company_review',
            field=models.IntegerField(choices=[(1, 'Onestar'), (2, 'Twostar'), (3, 'Threestar'), (4, 'fourstar'), (5, 'fivestar')], null=True),
        ),
    ]
