# Generated by Django 3.1.6 on 2021-02-22 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0002_auto_20210222_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='service_category_id',
            new_name='service_category',
        ),
    ]
