# Generated by Django 3.1.6 on 2021-02-09 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0002_auto_20210208_1108'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Area',
        ),
    ]
