# Generated by Django 3.1.6 on 2021-02-24 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0003_auto_20210222_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigndatacollector',
            name='service_category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='sadmin.servicecategory'),
        ),
        migrations.AlterField(
            model_name='collectdata',
            name='package_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='sadmin.package'),
        ),
        migrations.AlterField(
            model_name='collectdata',
            name='service_category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='sadmin.servicecategory'),
        ),
    ]
