# Generated by Django 3.1.6 on 2021-03-06 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0004_auto_20210224_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigndatacollector',
            name='assign_data_collector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sadmin.surveyor'),
        ),
    ]
