# Generated by Django 3.1.6 on 2021-02-14 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0004_auto_20210213_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subdistrict',
            old_name='subdistrct_name',
            new_name='sub_district_name',
        ),
    ]
