# Generated by Django 3.1.6 on 2021-03-06 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0006_auto_20210306_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigndatacollector',
            name='country',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sadmin.country'),
        ),
        migrations.AlterField(
            model_name='assigndatacollector',
            name='district',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sadmin.district'),
        ),
        migrations.AlterField(
            model_name='assigndatacollector',
            name='division',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sadmin.division'),
        ),
        migrations.AlterField(
            model_name='assigndatacollector',
            name='sub_district',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sadmin.subdistrict'),
        ),
    ]
