# Generated by Django 3.1.6 on 2021-03-06 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0008_auto_20210306_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigndatacollector',
            name='country',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sadmin.country'),
        ),
    ]
