# Generated by Django 3.1.6 on 2021-03-06 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0009_auto_20210306_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigndatacollector',
            name='country',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='sadmin.country'),
        ),
        migrations.AlterField(
            model_name='assigndatacollector',
            name='data_collector',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='sadmin.surveyor'),
        ),
        migrations.AlterField(
            model_name='assigndatacollector',
            name='district',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='sadmin.district'),
        ),
        migrations.AlterField(
            model_name='assigndatacollector',
            name='division',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='sadmin.division'),
        ),
        migrations.AlterField(
            model_name='assigndatacollector',
            name='sub_district',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='sadmin.subdistrict'),
        ),
    ]
