# Generated by Django 3.1.6 on 2021-03-07 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0010_auto_20210306_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigndatacollector',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sadmin.country'),
        ),
        migrations.AlterField(
            model_name='assigndatacollector',
            name='data_collector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sadmin.surveyor'),
        ),
        migrations.AlterField(
            model_name='assigndatacollector',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sadmin.district'),
        ),
        migrations.AlterField(
            model_name='assigndatacollector',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sadmin.division'),
        ),
        migrations.AlterField(
            model_name='assigndatacollector',
            name='service_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sadmin.servicecategory'),
        ),
        migrations.AlterField(
            model_name='assigndatacollector',
            name='sub_district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sadmin.subdistrict'),
        ),
        migrations.AlterField(
            model_name='collectdata',
            name='package_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sadmin.package'),
        ),
        migrations.AlterField(
            model_name='collectdata',
            name='picture_visited_person',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='collectdata',
            name='service_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sadmin.servicecategory'),
        ),
    ]
