# Generated by Django 3.1.6 on 2021-03-08 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sadmin', '0011_auto_20210307_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectdata',
            name='company_review',
            field=models.IntegerField(choices=[(1, 'OneStar'), (2, 'TwoStar'), (3, 'ThreeStar'), (4, 'FourStar'), (5, 'FiveStar')], default=1),
        ),
        migrations.AlterField(
            model_name='collectdata',
            name='data_collector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
