# Generated by Django 3.1.6 on 2021-03-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0012_auto_20210308_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectdata',
            name='company_review',
            field=models.IntegerField(choices=[(1, 'OneStar'), (2, 'TwoStar'), (3, 'ThreeStar'), (4, 'FourStar'), (5, 'FiveStar')]),
        ),
    ]
