# Generated by Django 3.1.6 on 2021-03-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0013_auto_20210308_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyor',
            name='profile_picture',
            field=models.ImageField(default='/img/default.png', upload_to=''),
        ),
    ]
