# Generated by Django 3.1.6 on 2021-03-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0014_auto_20210309_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectdata',
            name='picture_of_visiting_card',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='collectdata',
            name='picture_visited_person',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='surveyor',
            name='profile_picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
