# Generated by Django 3.1.6 on 2021-03-13 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0015_auto_20210309_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectdata',
            old_name='package_name',
            new_name='package',
        ),
    ]
