# Generated by Django 3.1.6 on 2021-03-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0016_auto_20210313_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('notice_desc', models.CharField(max_length=1000)),
                ('notice_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
