# Generated by Django 3.1.6 on 2021-03-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0017_noticeboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectdata',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='collectdata',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
