# Generated by Django 3.1.6 on 2021-03-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0018_auto_20210321_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('app_username', models.CharField(blank=True, max_length=256, null=True)),
                ('user_fullname', models.CharField(blank=True, max_length=256, null=True)),
                ('device_username', models.CharField(blank=True, max_length=256, null=True)),
                ('device_name', models.CharField(blank=True, max_length=256, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=256, null=True)),
                ('request_sender_app', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
